application:
  debug: true
  save:
    metrics:
      filename: currentMetrics_04.json
ibm:
  mq:
    queueManager: TSTQPD01
    channel: MQ.MONITOR.SSL1
    connName: localhost(1414)
    sslCipherSpec: TLS_RSA_WITH_AES_256_CBC_SHA256
    useSSL: true
    user: 
    password: 
    objects:
      queues:
        include: "*"
        exclude: SYSTEM.,AMQ.,DUMMY,ERROR.HANDLER
      channels:
        include: "*"
        exclude: SYSTEM.
      listeners:
        include: "*"
        exclude: SYSTEM.
        types:
          include: TCP
          exclude: "*" 
    event:
      delayInMilliSeconds: 10000      
    security:
      truststore: C:\ProgramData\IBM\MQ\qmgrs\TSTQPD01\ssl\tstqpd01jks.jks
      truststore-password: Passw0rd
      keystore: C:\ProgramData\IBM\MQ\qmgrs\TSTQPD01\ssl\tstqpd01jks.jks
      keystore-password: Passw0rd
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    health:
      show-details: always        
  security:
    enabled: false
info:
  app:
    name: MQ-Metrics
    description: IBM MQ Metrics
    version: 1.0.0.0
    java:
      version: 1.8.0.0
server:
  port:
    8083