application:
  debug: true
  save:
    metrics:
      filename: c:\Users\mickm\OneDrive\Documents\Development\Docker\mq-metrics\currentMetrics_04.json
ibm:
  mq:
    queueManager: QMAP01
    channel: MQ.MONITOR.SVRCONN
    connName: localhost(1480)
    sslCipherSpec: notused
    sslCipherSpec1: TLS_RSA_WITH_AES_256_CBC_SHA256
    useSSL: false
    user: mickm
    password: cartacat97
    objects:
      queues:
        include: "*"
        exclude: SYSTEM.,AMQ.,DUMMY,ERROR.HANDLER
      channels:
        include: "*"
        exclude: SYSTEM.
      listeners:
        include: "*"
        exclude: SYSTEM.
        types:
          include: TCP
          exclude: "*" 
    event:
      delayInMilliSeconds: 10000      
    security:
      truststore: notused
      truststore-password: notused
      keystore: notused
      keystore-password: notused
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    health:
      show-details: always        
  security:
    enabled: false
info:
  app:
    name: MQ-Metrics
    description: IBM MQ Metrics
    version: 1.0.0.0
    java:
      version: 1.8.0.0
server:
  port:
    8103